version: "3.4"
# Exposed ports
# ganache       localhost:8545

services:
  ganachecli:
    image: trufflesuite/ganache-cli:latest
    ports:
      - 8545:8545
    command: -m "candy maple cake sugar pudding cream honey rich smooth crumble sweet treat" -i 4448 -h 0.0.0.0 --db "./db"
    volumes:
      - ./ganache-volumes/ganache-storage:/app/db