openapi: '3.0.3'
info:
  description: The API of the i3Market Verifiable Credential service. 
  version: 1.0.0
  title: i3-market Verifiable Credential service API  
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'

tags:
  - name: Credential
    description: Credential endpoint
  - name: Issuer
    description: Issuer endpoint

servers:
- url: "{method}://{url}{contextPath}"
  description: The url of the running instance in the server
  variables:
    method:
      default: http
      description: http or https
    url:
      default: localhost:4200
      description: server url
    contextPath:      
      default: /release2/vc
      description: context path

paths:
  /credential:    
    get:
      summary: Get the credential list
      description: Get the credential list
      tags:
        - Credential          
      responses:
        200:
          description: Credential list
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
        500:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "./schema/error.yaml#/Error"

  /credential/issue/{credential}/callbackUrl/{callbackUrl}:    
    get:
      summary: Create a new credential with Veramo framework and store it in the wallet (full flow)
      description: Create a new credential with Veramo framework it in the wallet (full flow)
      tags:
        - Credential 
      parameters:           
        - name: credential
          in: path
          description: the credential JSON in encoded way
          required: true
          schema: {
            type: string
          }
        - name: callbackUrl
          in: path
          description: the callbackUrl in encoded way
          required: true
          schema: {
            type: string
          }                       
      responses:
        200:
          description: html page
          content: 
            text/html:
              schema: {
                type: string
              }
        500:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "./schema/error.yaml#/Error"

  /credential/issue/{did}/{credential}:    
    get:
      summary: Generate a new credential with Veramo framework for a specific did
      description: Create a new credential with Veramo framework for a specific did
      tags:
        - Credential 
      parameters:     
        - name: did
          in: path
          description: did user for which to create the verifiable credential
          required: true
          schema: {
            type: string
          }      
        - name: credential
          in: path
          description: the credential JSON in encoded way
          required: true
          schema: {
            type: string
          }                               
      responses:
        200:
          description: W3C credential in string format
          content: 
            application/json:
              schema: 
                type: object
        500:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "./schema/error.yaml#/Error"

  /credential/revoke:
    post:
      summary: Revoke a credential by JWT 
      tags:
        - Credential  
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                credentialJwt:
                  type: string        
      responses:
        200:
          description: Revoke operation status
          content:
            application/json:
              schema: 
                type: object
        500:
          description: Internal server error   

  /credential/verify:
    post:
      summary: Verify a credential by JWT 
      tags:
        - Credential 
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                credentialJwt:
                  type: string
                credentialIssuer:
                  type: string
      responses:
        200:
          description: Verify operation status
          content:
            application/json:
              schema: 
                type: object
        500:
          description: Internal server error 

  #/presentation/verify:
  #  post:
  #    summary: Verify a verifiable presentation by JWT. Used by OIDC authorization server during the authorization code flow 
  #    tags:
  #      - Presentation   
  #    requestBody:
  #      required: true
  #      content:
  #        application/json:
  #          schema:
  #            type: object
  #            properties:
  #              presentationJwt:
  #                type: string                    
  #    responses:
  #      200:
  #        description: Verify operation status
  #      500:
  #        description: Internal server error

  /issuer/subscribe:
    get:
      summary: Subscribe this issuer in the i3market trusted issuers list
      tags:
        - Issuer    
      responses:
        200:
          description: Subscribe operation successful
          content:
            application/json:
              schema: 
                type: object
        500:
          description: Internal server rrror

  /issuer/unsubscribe:
    get:
      summary: Unsubscribe this issuer from the i3market trusted issuers list
      tags:
        - Issuer                  
      responses:
        200:
          description: Unsubscribe operation successful
          content:
            application/json:
              schema: 
                type: object
        500:
          description: Internal server error

  /issuer/verify:
    get:
      summary: Verify the subscription status of the issuer
      tags:
        - Issuer                 
      responses:
        200:
          description: Registration status of the issuer
          content:
            application/json:
              schema: 
                type: object
        500:
          description: Internal server error

components:
  securitySchemes:
    BasicAuth:
      $ref: "./security-schemes/basic.yaml#/basicAuth"