openapi: '3.0.3'
info:
  description: The API of the i3Market Verifying Credential service. 
  version: 1.0.0
  title: i3-market Verifiable Credential service API  
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'

tags:
  - name: DID
    description: DID endpoint
  - name: Credential
    description: Credential endpoint
  - name: Presentation
    description: Presentation endpoint
  - name: Issuer
    description: Issuer endpoint
  
  

paths:
  /release2/vc/did/{callbackUrl}:    
    get:
      summary: Obtain the user DID - uPort flow
      description: QR to scan in order to retrive the user's DID      
      tags:
        - DID
      security:
        - BasicAuth: []
      parameters:
        - name: callbackUrl
          in: path
          description: Callback url
          required: true
          type: string     
      deprecated: true	     
      responses:
        200:
          description: User's did          
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "./schema/error.yaml#/Error"

  /release2/vc/credential:    
    get:
      summary: Get the credential list
      description: Get the credential list
      tags:
        - Credential
      security:
        - BasicAuth: []            
      responses:
        200:
          description: Credential list
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "./schema/error.yaml#/Error"

  /release2/vc/credential/issue/{credential}:    
    get:
      summary: Create a new credential with Veramo framework
      description: Create a new credential with Veramo framework
      tags:
        - Credential
      security:
        - BasicAuth: []  
      parameters:           
        - name: credential
          in: path
          description: the credential JSON in encoded way
          required: true
          type: string             
      responses:
        200:
          description: Credential list
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "./schema/error.yaml#/Error"

  /release2/vc/credential/issue/{did}:
    post:
      summary: Create a credential for DID - uPort flow
      description: QR code to scan in order to add a verifiable credential       
      tags:
        - Credential
      security:
        - BasicAuth: []
      parameters:               
        - name: did
          in: path
          description: DID of the user
          required: true
          type: string  
      deprecated: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                credential:
                  type: string              
      responses:
        200:
          description: QR code of the credential
        500:
          description: Internal server error
    
  /release2/vc/credential/revoke:
    post:
      summary: Revoke a credential by JWT 
      tags:
        - Credential 
      security:
        - BasicAuth: []    
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                credentialJwt:
                  type: string        
      responses:
        200:
          description: Revoke operation status
        500:
          description: Internal server error   

  /release2/vc/credential/verify:
    post:
      summary: Verify a credential by JWT 
      tags:
        - Credential 
      security:
        - BasicAuth: []    
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                credentialJwt:
                  type: string
                credentialIssuer:
                  type: string
      responses:
        200:
          description: Verify operation status
        500:
          description: Internal server error 
      
  /release2/vc/presentation/verify:
    post:
      summary: Verify a verifiable presentation by JWT. Used by OIDC authorization server during the authorization code flow 
      tags:
        - Presentation 
      security:
        - BasicAuth: []    
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                presentationJwt:
                  type: string                    
      responses:
        200:
          description: Verify operation status
        500:
          description: Internal server error

  /release2/vc/issuer/subscribe:
    get:
      summary: Subscribe this issuer in the i3market trusted issuers list
      tags:
        - Issuer 
      security:
        - BasicAuth: []          
      responses:
        200:
          description: Subscribe operation successful
        500:
          description: Internal server rrror
  
  /release2/vc/issuer/unsubscribe:
    get:
      summary: Unsubscribe this issuer from the i3market trusted issuers list
      tags:
        - Issuer 
      security:
        - BasicAuth: []                   
      responses:
        200:
          description: Unsubscribe operation successful
        500:
          description: Internal server error

  /release2/vc/issuer/verify:
    get:
      summary: Verify the subscription status of the issuer
      tags:
        - Issuer 
      security:
        - BasicAuth: []                   
      responses:
        200:
          description: Registration status of the issuer
        500:
          description: Internal server error

components:
  securitySchemes:
    BasicAuth:
      $ref: "./security-schemes/basic.yaml#/basicAuth"