openapi: '3.0.3'
info:
  description: The API of the i3Market Verifying Credential service. 
  version: 1.0.0
  title: i3-market Verifying Credential service API  
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'

tags:
  - name: DID
    description: DID endpoint
  - name: Credential
    description: Credential endpoint

paths:
  /did/{callbackUrl}:    
    get:
      summary: Obtain the user DID
      description: QR to scan in order to retrive the user's DID      
      tags:
        - DID
      security:
        - BasicAuth: []
      parameters:
        - name: callbackUrl
          in: path
          description: Callback url
          required: true
          type: string          
      responses:
        200:
          description: User's did          
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "./schema/error.yaml#/Error"

  /credential/issue/{did}:
    post:
      summary: Create a credential for DID
      description: QR code to scan in order to add a verifiable credential       
      tags:
        - Credential
      security:
        - BasicAuth: []
      parameters:               
        - name: did
          in: path
          description: DID of the user
          required: true
          type: string  
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                credential:
                  type: string              
      responses:
        200:
          description: QR code of the credential
        default:
          description: unexpected error          
    
  /credential/revoke:
    post:
      summary: Revoke a credential by JWT 
      tags:
        - Credential 
      security:
        - BasicAuth: []    
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                credential:
                  type: string        
      responses:
        200:
          description: Revoke operation status
        default:
          description: unexpected error   

  /credential/verify:
    post:
      summary: Verify a credential by JWT 
      tags:
        - Credential 
      security:
        - BasicAuth: []    
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                credential:
                  type: string        
      responses:
        200:
          description: Verify operation status
        default:
          description: unexpected error   

components:
  securitySchemes:
    BasicAuth:
      $ref: "./security-schemes/basic.yaml#/basicAuth"